services:
  db:
    image: postges_ru
    build:
      context: ./postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    env_file:
      - ./postgres/.env


  pinger:
    image: pg_pinger
    build:
      context: ./app
    restart: always
    env_file:
      - ./app/.env
    volumes:
      - ./pinger_logs:/app/logs
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
